# Generated by Django 5.1.7 on 2025-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeneuralensinar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField(verbose_name='Número 1')),
                ('num2', models.IntegerField(verbose_name='Número 2')),
                ('operation', models.IntegerField(choices=[(0, 'Adição'), (1, 'Subtração'), (2, 'Multiplicação'), (3, 'Divisão')], verbose_name='Operação')),
                ('student_answer', models.IntegerField(verbose_name='Resposta do Aluno')),
                ('correct_answer', models.IntegerField(verbose_name='Resposta Correta')),
                ('is_correct', models.BooleanField(verbose_name='Está Correta?')),
                ('feedback_message', models.TextField(verbose_name='Mensagem de Feedback')),
                ('explanation', models.TextField(verbose_name='Explicação')),
                ('step_by_step', models.TextField(blank=True, null=True, verbose_name='Passo a Passo')),
                ('error_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Erro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
    ]
